# .rubocop.yml
AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

# Omakase-inspired settings
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

# Your custom overrides
Style/StringLiterals:
  Enabled: false

Style/Sample:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
Layout/EmptyLines:
  Enabled: false

Layout/LineLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'spec/**/*'

Lint/EmptyBlock:
  Enabled: false
